export const CRISIS_STATS = [
  {
    id: "datasets",
    value: 85,
    suffix: "%",
    label: "Training datasets sourced from North America & Europe",
    icon: "🌍",
    color: "danger",
  },
  {
    id: "cardiac",
    value: 75,
    suffix: "%",
    label: "Cardiovascular AI models trained on male-only data",
    icon: "❤️",
    color: "danger",
  },
  {
    id: "skin",
    value: 4.5,
    suffix: "%",
    label: "Dermatology datasets represent dark skin tones",
    icon: "🔬",
    color: "danger",
  },
  {
    id: "sepsis",
    value: 3,
    suffix: "×",
    label: "Higher sepsis false-negative rate for minority patients",
    icon: "⚠️",
    color: "danger",
  },
];

export const FAILURE_STORIES = [
  {
    id: "skin-cancer",
    title: "Skin Cancer Misdiagnosis",
    location: "India & Sub-Saharan Africa",
    locationFlag: "🌏",
    problem: "AI dermatology tools trained predominantly on light-skinned images fail to detect melanoma and other skin cancers in darker skin tones, leading to late-stage diagnoses.",
    rootCause: "Dataset imbalance — less than 4.5% of training images feature Fitzpatrick skin types V–VI.",
    humanImpact: "Patients receive delayed or incorrect diagnoses, dramatically reducing survival rates. In regions with limited specialist access, this AI is the only 'doctor' available.",
    stat: "4.5% dark skin representation",
    statColor: "danger",
    icon: "🔬",
    gradient: "from-orange-900/30 to-red-900/20",
    borderColor: "border-red-500/30",
  },
  {
    id: "cardiac-women",
    title: "Cardiac Risk in Women",
    location: "Global",
    locationFlag: "🌐",
    problem: "Heart disease AI models underestimate risk in women because symptoms differ from the male-centric training data. Women are 50% more likely to be misdiagnosed after a heart attack.",
    rootCause: "Gender bias — 75% of cardiovascular studies historically enrolled male-only cohorts, embedding this bias into every derived AI model.",
    humanImpact: "Women leave hospitals with 'anxiety' diagnoses when they're having cardiac events. Thousands die annually from preventable heart disease mismanaged by biased AI.",
    stat: "50% higher misdiagnosis rate",
    statColor: "danger",
    icon: "❤️",
    gradient: "from-red-900/30 to-pink-900/20",
    borderColor: "border-red-500/30",
  },
  {
    id: "pulse-oximeter",
    title: "Pulse Oximeter Bias",
    location: "United States",
    locationFlag: "🇺🇸",
    problem: "FDA-cleared pulse oximeters overestimate oxygen levels in patients with darker skin, missing dangerous hypoxemia (low blood oxygen) that requires immediate intervention.",
    rootCause: "Hardware bias — devices were designed and calibrated using homogeneous light-skinned populations. This bias transfers into AI diagnostic systems trained on this flawed data.",
    humanImpact: "During COVID-19, Black and Hispanic patients were undertreated for hypoxemia at critical rates. Studies confirmed threefold higher risk of occult hypoxemia in darker-skinned patients.",
    stat: "3× undetected hypoxemia risk",
    statColor: "danger",
    icon: "💓",
    gradient: "from-purple-900/30 to-red-900/20",
    borderColor: "border-purple-500/30",
  },
  {
    id: "mental-health",
    title: "Mental Health Cultural Bias",
    location: "East & Southeast Asia",
    locationFlag: "🌏",
    problem: "NLP-based mental health AI tools built on Western DSM frameworks misclassify or miss culturally-specific presentations of depression and anxiety in Asian communities.",
    rootCause: "Cultural bias — mental health datasets, language models, and diagnostic frameworks are overwhelmingly Western, missing somatic expression patterns common in AAPI communities.",
    humanImpact: "AAPI patients who express depression through physical symptoms (fatigue, pain) are dismissed or misdiagnosed. Suicide rates in these communities have risen while AI tools claim 'no mental health risk'.",
    stat: "60% cultural context mismatch",
    statColor: "cyan",
    icon: "🧠",
    gradient: "from-blue-900/30 to-cyan-900/20",
    borderColor: "border-cyan-500/30",
  },
  {
    id: "zipcode",
    title: "ZIP Code Discrimination",
    location: "United States",
    locationFlag: "🇺🇸",
    problem: "A widely-deployed healthcare algorithm used ZIP code as a proxy for risk, systematically directing fewer resources and less care to Black patients — even when they were sicker than white patients.",
    rootCause: "Proxy bias — the model optimized for 'cost' as a proxy for 'health need', embedding historical racial wealth disparities directly into medical decision-making.",
    humanImpact: "73 million people were subject to this biased algorithm. Black patients had to be significantly sicker than white patients to receive the same level of care referrals.",
    stat: "73 million patients affected",
    statColor: "danger",
    icon: "📍",
    gradient: "from-yellow-900/30 to-orange-900/20",
    borderColor: "border-yellow-500/30",
  },
];

export const ROOT_CAUSES = [
  {
    id: "dataset",
    title: "Dataset Imbalance",
    icon: "📊",
    description: "Training data over-represents wealthy, white, male populations from North America and Europe. Models inherit these skews as ground truth.",
    severity: 95,
  },
  {
    id: "proxy",
    title: "Proxy Bias",
    icon: "🔗",
    description: "Using socioeconomic variables like ZIP code, insurance type, or cost as proxies for health need encodes historical racial and economic inequalities.",
    severity: 85,
  },
  {
    id: "hardware",
    title: "Hardware Bias",
    icon: "🔧",
    description: "Medical devices calibrated on homogeneous populations produce biased measurements that propagate through AI training pipelines as 'ground truth'.",
    severity: 78,
  },
  {
    id: "cultural",
    title: "Cultural Bias",
    icon: "🌐",
    description: "Western-centric diagnostic frameworks and language models miss culturally-specific symptom presentations, leading to misclassification across diverse populations.",
    severity: 82,
  },
  {
    id: "gender",
    title: "Gender Bias",
    icon: "⚖️",
    description: "Decades of male-centric medical research created training sets that systematically underrepresent female physiology, creating diagnostic blind spots for women.",
    severity: 88,
  },
];

export const SOLUTION_FEATURES = [
  {
    id: "bias-detection",
    title: "Bias Detection Engine",
    description: "Automated multi-axis fairness scanning across demographic groups before any model reaches production. Detects disparate impact, statistical parity violations, and intersectional biases.",
    icon: "🔍",
    color: "cyan",
  },
  {
    id: "fairness-audit",
    title: "Fairness Audit Dashboard",
    description: "Real-time monitoring of model decisions across gender, ethnicity, age, and geography. Continuous drift detection with automated alerting when fairness thresholds are breached.",
    icon: "📊",
    color: "blue",
  },
  {
    id: "dataset-validation",
    title: "Diverse Dataset Validation",
    description: "Cryptographically verifiable dataset diversity certificates. Automated gap analysis identifies underrepresented populations and triggers targeted data collection.",
    icon: "🌍",
    color: "cyan",
  },
  {
    id: "explainable-ai",
    title: "Explainable AI Decision Layer",
    description: "Every AI recommendation includes a plain-language explanation of which factors drove the decision, enabling clinicians to identify and override biased reasoning.",
    icon: "🧠",
    color: "blue",
  },
  {
    id: "cultural-adaptation",
    title: "Cultural-Language Adaptation",
    description: "Localized NLP models trained on region-specific medical language, symptom vocabularies, and cultural health frameworks — ensuring AI works for every community.",
    icon: "🌐",
    color: "cyan",
  },
  {
    id: "fairness-scoring",
    title: "Real-time Fairness Scoring",
    description: "Live demographic equity scores for every clinical decision. Automatic flags when model confidence diverges across demographic groups for the same presentation.",
    icon: "⚡",
    color: "blue",
  },
];

export const HOW_IT_WORKS_STEPS = [
  {
    id: "ingestion",
    step: "01",
    title: "Data Ingestion",
    description: "Structured and unstructured clinical data from EHRs, imaging, and IoT devices is ingested with demographic metadata preserved.",
    icon: "📥",
    color: "#0A84FF",
  },
  {
    id: "scanner",
    step: "02",
    title: "Bias Scanner",
    description: "Multi-metric fairness analysis runs automatically — checking for disparate impact, equalized odds, and calibration across all demographic intersections.",
    icon: "🔍",
    color: "#00FFD1",
  },
  {
    id: "correction",
    step: "03",
    title: "Fairness Correction",
    description: "Adversarial debiasing, reweighting, and synthetic minority oversampling (SMOTE) techniques are applied based on detected bias type and severity.",
    icon: "⚖️",
    color: "#0A84FF",
  },
  {
    id: "explainability",
    step: "04",
    title: "Explainability Engine",
    description: "SHAP values and attention maps generate human-readable explanations for every decision, mapped to specific clinical features — not demographic proxies.",
    icon: "🧠",
    color: "#00FFD1",
  },
  {
    id: "output",
    step: "05",
    title: "Ethical Decision Output",
    description: "Clinicians receive AI recommendations with fairness scores, confidence intervals per demographic group, and flagged potential biases for review.",
    icon: "✅",
    color: "#0A84FF",
  },
];

export const IMPACT_METRICS = [
  { label: "Reduction in false negatives for minorities", value: 67, target: 67, color: "#00FFD1" },
  { label: "Improvement in cross-demographic accuracy", value: 89, target: 89, color: "#0A84FF" },
  { label: "Countries with equitable coverage", value: 94, target: 94, color: "#00FFD1" },
  { label: "Physician trust & adoption score", value: 92, target: 92, color: "#0A84FF" },
];

export const CHART_DATA = [
  { name: "White Male", before: 94, after: 94 },
  { name: "White Female", before: 81, after: 93 },
  { name: "Black Male", before: 72, after: 91 },
  { name: "Black Female", before: 64, after: 90 },
  { name: "Hispanic", before: 69, after: 91 },
  { name: "Asian", before: 76, after: 92 },
  { name: "Indigenous", before: 58, after: 89 },
];
